# Generated by Django 3.2.2 on 2021-05-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fse_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_confirmed',
        ),
        migrations.AlterField(
            model_name='device',
            name='last_humidity',
            field=models.IntegerField(default=0, verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_temperature',
            field=models.IntegerField(default=0, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='fse_server.location'),
        ),
    ]
