# Generated by Django 3.2.2 on 2021-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fse_server', '0002_auto_20210515_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinput',
            name='last_state',
            field=models.IntegerField(default=0, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='deviceoutput',
            name='last_state',
            field=models.IntegerField(default=0, verbose_name='State'),
        ),
    ]
