# Generated by Django 3.2.2 on 2021-05-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fse_server', '0003_auto_20210516_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinput',
            name='alarm_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.IntegerField(default=0, verbose_name='Target Value')),
                ('mode', models.IntegerField(choices=[(0, 'EQUAL TO'), (1, 'GREATER THAN'), (2, 'GREATER OR EQUAL THAN'), (3, 'LOWER THAN'), (4, 'LOWER OR EQUAL THAN')])),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='fse_server.deviceinput')),
            ],
        ),
    ]
